{
  "sample_proj":
    {
      "target": "modal",
      "outputs":
        {
          "modal":
            {
              "type": "duckdb",
              "path": "/tmp/dbt.duckdb",
              "extensions": ["httpfs", "parquet"],
              "settings":
                {
                  "s3_region": "us-east-1",
                  "s3_access_key_id": "{{ env_var('AWS_ACCESS_KEY_ID') }}",
                  "s3_secret_access_key": "{{ env_var('AWS_SECRET_ACCESS_KEY') }}",
                },
            },
        },
    },
}
