// At least one prompt for every letter of the alphabet, and
// partially curated to generate good-looking Pokémon cards.
//
// Further curation of the list by removing unappealing prompts, adding good prompts,
// or editing existing prompts is welcome.
export const prompts = [
  "Abraham Lincoln",
  "Air Jordans",
  "A Happy Baby With A Rattle",
  "Banana in Pajamas",
  "Crab Made of Cheese",
  "Donald Trump",
  "Duck sized horse",
  "Elephant With Six Legs",
  "Frodo Baggins",
  "Golden Seal",
  "Homer Simpson",
  "Horse sized duck",
  "IPhone 7 Device",
  "Joker Evil",
  "King Kong",
  "Kung Fu Panda",
  "Lima Monkey",
  "Marvin The Paranoid Robot",
  "Modal Lab Mad Scientist",
  "Nocturnal Animal",
  "Old Buddhist Monk in Orange Robes", // A+ prompt.
  "PDP-11 Computer",
  "Power Couple",
  "Question Mark With Eyes",
  "Roomba",
  "Rage Against The Machine",
  "Snake With Metal Wings",
  "Suit of Armor Alligator",
  "Steve Jobs",
  "The Devil",
  "The Fear",
  "Uranus The Planet",
  "Vladimir Lenin",
  "Willy Wonka Cat",
  "Xenomorph Alien",
  "Yoyo Toy",
  "Zoro The Masked Bandit",
];
