# # Run evals on 1,000 Modal Sandboxes
#
# [Modal Sandboxes](https://modal.com/docs/guide/sandboxes) are useful for executing code generated by a language model,
# creating isolated environments for running untrusted code, etc.
# Here, we use [Harbor](https://www.harborframework.com/docs), a framework for evaluating and optimizing agents and models in container environments,
# to demonstrate how to run massively parallel evals.

import os
import subprocess
from pathlib import Path

import modal

app = modal.App("example-sandboxes")
image = modal.Image.debian_slim(python_version="3.12").uv_pip_install(
    "harbor[modal]==0.15.0"
)
modal_config_path = Path.home() / ".modal.toml"
if modal_config_path.exists():
    image = image.add_local_file(modal_config_path, "/root/.modal.toml", copy=True)
secrets = []
if os.environ.get("MODAL_TOKEN_ID") and os.environ.get("MODAL_TOKEN_SECRET"):
    secrets.append(
        modal.Secret.from_local_environ(["MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET"])
    )

# to store generated artifacts


volume = modal.Volume.from_name("example-sandboxes", create_if_missing=True)
RUNS_PATH = Path("/runs")

# harbor setup


TASK_FILES = {
    "task.toml": """version = "1.0"
[environment]
docker_image = "ubuntu:24.04"
workdir = "/app"
network_mode = "no-network"
cpus = 1
memory_mb = 512
storage_mb = 1024
""",
    "instruction.md": "Create `answer.txt` containing exactly `ok`.\n",
    "solution/solve.sh": "#!/bin/bash\nprintf 'ok\\n' > answer.txt\n",
    "tests/test.sh": """#!/bin/bash
if [ "$(cat /app/answer.txt 2>/dev/null)" = "ok" ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
  exit 1
fi
""",
}


@app.function(
    image=image,
    volumes={RUNS_PATH: volume},
    secrets=secrets,
)
def run_evals(trials: int, concurrency: int) -> tuple[int, int]:
    # write task files
    run_dir = RUNS_PATH / os.urandom(16).hex()
    task, jobs = run_dir / "task", run_dir / "jobs"
    (task / "environment").mkdir(parents=True)
    for name, contents in TASK_FILES.items():
        path = task / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents)
        if name.endswith(".sh"):
            path.chmod(0o755)

    print(f"Running {trials} trials on {concurrency} concurrent Modal Sandboxes...")
    subprocess.run(
        [
            "harbor",
            "run",
            "--path",
            str(task),
            "--agent",
            "oracle",
            "--env",
            "modal",
            "--n-attempts",
            str(trials),
            "--n-concurrent",
            str(concurrency),
            "--jobs-dir",
            str(jobs),
            "--yes",
            "--quiet",
        ],
        check=True,
    )

    rewards = [path.read_text().strip() for path in jobs.glob("**/reward.txt")]
    return sum(reward == "1" for reward in rewards), len(rewards)


@app.local_entrypoint()
def main(
    n_parallel: int = 1000,
):
    trials = concurrency = n_parallel
    passed, total = run_evals.remote(trials, concurrency)
    print(f"{passed}/{total} tests passed")
