version: 2

sources:
  - name: external_source
    meta:
      external_location: "s3://modal-example-dbt-duckdb/sources/{name}.parquet"
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments
